// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsCelEYtlsPI7x05ObF6gcr5vaGD0jSOs',
    appId: '1:525310605691:web:ccfb94802e01b47a0b25de',
    messagingSenderId: '525310605691',
    projectId: 'fcm-push-lab6',
    authDomain: 'fcm-push-lab6.firebaseapp.com',
    storageBucket: 'fcm-push-lab6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUaZGQWwmp2oOGlZw-qYY2-CPe_Bb5IPg',
    appId: '1:525310605691:android:0ecc66ba776b6c7b0b25de',
    messagingSenderId: '525310605691',
    projectId: 'fcm-push-lab6',
    storageBucket: 'fcm-push-lab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7cqLfSwEwiGBhJzm1YYWyWM1_M7Xch6g',
    appId: '1:525310605691:ios:527ec966245bd3180b25de',
    messagingSenderId: '525310605691',
    projectId: 'fcm-push-lab6',
    storageBucket: 'fcm-push-lab6.firebasestorage.app',
    iosBundleId: 'com.example.fcmPushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7cqLfSwEwiGBhJzm1YYWyWM1_M7Xch6g',
    appId: '1:525310605691:ios:527ec966245bd3180b25de',
    messagingSenderId: '525310605691',
    projectId: 'fcm-push-lab6',
    storageBucket: 'fcm-push-lab6.firebasestorage.app',
    iosBundleId: 'com.example.fcmPushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsCelEYtlsPI7x05ObF6gcr5vaGD0jSOs',
    appId: '1:525310605691:web:61a3d2373b23cb8d0b25de',
    messagingSenderId: '525310605691',
    projectId: 'fcm-push-lab6',
    authDomain: 'fcm-push-lab6.firebaseapp.com',
    storageBucket: 'fcm-push-lab6.firebasestorage.app',
  );
}
